
def main():
    print("Surviving in college!")
    print("Welcome to your new college and congratulation on your first day here!")
    print("Your main goal is to go through all 10 locations and survive...")
    name = input("To continue, enter your name: ")
    print("Okay, " + name + ". Nice to meet you! We will start from the first location - residence hall.")
    print("Here you will be living with your roommate! Be sure that you know how to share space with other people.")
    input("Press ENTER to continue")
    print("You will have more time to decorate your room, now let's move forward.")
    print("We are now in the park. Here you can make your homework or hang out with your classmates")
    input("Press ENTER to continue")
    print("Our next stop will be library. Here you can find a tone of different books")
    print("As well it could be quite place to study")
    input("Press ENTER to continue")
    print("Well..I know you are tired and hungry, right?")
    print("Here is the dining hall!")
    print("You can choose any food you want and fill yourself with energy")
    input("Press ENTER to continue")
    print("Probably, the next place is where you will spend most of your time")
    print("This is the lecture halls and classrooms")
    print("In order to survive - make your homework and be present at the lectures")
    input("Press ENTER to continue")
    print("I know sometimes is hard to understand what you should do and understand your plan for tthe future")
    print("You can always come at the advisor office and ask the rule of the game or for hint")
    input("Press ENTER to continue")
    print("Sometimes you just nned to calm down and spend some time with yourself")
    print("The river is a perfect spot! Go here at any time you want to talk to yourself.")
    input("Press ENTER to continue")
    print("All events, information sessions, club activities, shows will be...")
    print("at the theater!")
    input("Press ENTER to continue")
    print("Now we are inside the gym, perfect place to keep yourself in good form")
    input("Press ENTER to continue")
    print("Our final stop will be at gallery")
    print("A lot of students participate in creating annual exhibitions")
    input("Press ENTER to continue")
    print ("You made this! Congratulations!")
    print ("It was not that hard, right, " + name + "?")
main()